name = "NeuroDynamics"
uuid = "ddade9f8-0711-45cc-a88e-9a30bd56782a"
authors = ["Ahmed El-Gazzar"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
