wandb_version: 1

architecture:
  desc: null
  value: CNN
dropout:
  desc: null
  value: 0.2
learning_rate:
  desc: null
  value: 0.01
dataset:
  desc: null
  value: CIFAR-100
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.4
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1721161937
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      - 61
      4: 3.11.5
      5: 0.17.4
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
